### ISSUE TITLE
Plan for larger model?

### ISSUE THREAD

**Issue by YixinSong-e** [arcee-ai/DistillKit#6]
Thanks for this nice project.
I would like to test on larger model. I'd also love to contribute code to the project, but I hope you can give me some suggestions. :)

**Comment by Nottlespike** [comment]
> Thanks for this nice project. I would like to test on larger model. I'd also love to contribute code to the project, but I hope you can give me some suggestions. :)

To give some context for larger models very large VRAM requirements locally I can only distill a single Llama 3.1/3 8B to TinyLlama 1.1B with DeepSpeed_Zero3_BF16 almost exactly maxing out 4 consumer 24GB GPU's/96GB of VRAM/4x3090 Ti FE's. I am currently attempting a logit based distillation from a Qwen 2 7B to Qwen 2 1.5B on this VRAM and DeepSpeed setup as well but am running into out of memory issues. It is possible that FDSP is more VRAM efficent and is afaik the only way to do it with a multi node setup but my local system has intermittent issues with FDSP over DeepSpeed.

**Comment by Crystalcareai** [comment]
We'll have more resources for larger models here shortly ~eta 1 week maybe
