### ISSUE TITLE
Teacher uses student tokenizer in distill_hidden.py

### ISSUE THREAD

**Issue by HeegonJin** [arcee-ai/DistillKit#7]
```
trainer = HiddenTrainer(
    model=student_model,
    train_dataset=dataset,
    max_seq_length=config["tokenizer"]["max_length"],
    tokenizer=student_tokenizer,
    dataset_text_field="text",
    args=training_arguments,
    packing=True,
)
```
the input is created from the student tokenizer for both teacher and student.
This should be a problem when teacher and student vocab mismatch, even for hidden distillation.

**Comment by fernando-neto-ai** [comment]
Issue solved with this PR: https://github.com/arcee-ai/DistillKit/pull/8

Waiting for merge from @Crystalcareai
